--- # This playbook is created to define all section in an ansible playbook 
# Target Section

- name: Install Lynx 
  user: cloud_user
  sudo: yes
#  become: yes
  gather_facts: no
  hosts: apacheweb

# Variable Section - Local variable, imported variable and runtime variable

  vars:
    app_server: apacheweb
    package_name: cowsay
  vars_files:
    - variables/variables.yml
  vars_prompt:
    - name: state
      prompt: Define State

# Tasks Section

  tasks:
    - name: date/time for starting the job
      command: date
      register: start_time

    - debug: var=start_time

    - name: Install {{ package_name }} at {{ app_server }}
      yum: pkg={{ package }}  state={{ state }}  update_cache=true
    
    - name: Install apache and restart httpd service
      action: yum name=httpd state=installed
      notify: Restart HTTPD

    - name: date / time for ending the job
      command: date
      register: end_time

    - debug: var=end_time

#Handdler Section

  handlers:
    - name: Restart HTTPD
      action: service name=httpd state=restarted
