---  #Example local action

- hosts: 127.0.0.1
  connection: local
  tasks:

# This task will be executed with local connection (CLI argument --local) instead of ssh or paramiko
  - name: Install Telnet
    yum: pkg=telnet state=latest
